### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by zachbuchanan** [HelloWorldKSU/Reminder-App#2]
Create mySQL db

**Comment by zachbuchanan** [comment]
Lets start by creating a rough schema table with the attributes we think we will need

**Comment by zachbuchanan** [comment]
A separate db "usersignups" has been created to record emails from temp landing page

**Comment by ikusner13** [comment]
I was thinking for now that we could do what you sketched out during the meeting, so a user table, and a task table. If we wanted our app to differentiate between a task/activity(has a start/due time) and just a regular note(no certain time), we could also have a note table. But idk if we're going for that implementation or not

**Comment by zachbuchanan** [comment]
This looks complete.
